import "./globals.css";
import { MesaProvider } from "../app/(sections)/context/MesaContext";

export const metadata = {
  title: "MENÚ DIGITAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <MesaProvider>
        {children}
      </MesaProvider>
      </body>
    </html>
  );
}
